### ISSUE TITLE
Usage example please

### ISSUE THREAD

**Issue by fikr4n** [ricardoalcocer/actionbarclone#4]
Hi, I am new to Titanium. I got this when trying to use ActionBar Clone:

```
[ERROR] :  TiExceptionHandler: (main) [2011,2011] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,2011] - In alloy/controllers/index.js:73,17
[ERROR] :  TiExceptionHandler: (main) [0,2011] - Message: Uncaught TypeError: Object #<Controller> has no method 'setActionButtons'
[ERROR] :  TiExceptionHandler: (main) [0,2011] - Source:     $.headerbar.setActionButtons(getExtraButtons());
[ERROR] :  V8Exception: Exception occurred at alloy/controllers/index.js:73: Uncaught TypeError: Object #<Controller> has no method 'setActionButtons'
```

Could you please give me an example of using this action bar? Actually, I need to make an action bar with (swipe-able) tab navigation.

**Comment by ricardoalcocer** [comment]
This project is an emulated ActionBar to be used on devices pre-Android 3.0, so its features are limited.  Titanium will soon support the "Android Support Library" (https://jira.appcelerator.org/browse/TIMOB-15021), which will make this project obsolete.

**Comment by fikr4n** [comment]
At least, I need your library before Titanium finish implementing it :). Also, I need it to be emulated in iOS.

**Comment by ricardoalcocer** [comment]
This whole Repo is an example on how to use it, but the actual implementation is here: https://github.com/ricardoalcocer/actionbarclone/blob/master/app/controllers/index.js

I wouldn't advise you to emulate it on iOS since the ActionBar is an android-only construct.  For iOS you should use the UINavigationController exposed by Titanium as NavigationWindow.
